config/routes.rb
Rainforest::Application.routes.draw do
  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :description, :name, :presence => true
	validates :price_in_cents, :numericality => {:only_integer => true}

	def formatted_price
		price_in_dollars = price_in_cents.to_f / 100
		sprintf("%2f", price_in_dollars)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
  	@products = Product.all
  end

  def show
  	@product = Product.find(params[:id])
  end

  def new
  	@product = Product.new
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def create
  	@product = Product.new(product_params)

  	if @product.save
  		redirect_to products_url
  	else
  	render :new
  	end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
  	@product = Product.find(params[:id])
  	@product.destroy
  	redirect_to products_path
  end

  private
  def product_params
  	params.require(:product).permit(:name, :description, :price_in_cents)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited from being saved:</h2>

      <ul>
      <% @product.errors.full_meggages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products (<%= @products.length %>)</h1>
<%= link_to "New Product", "/products/new" %>

<% @products.each do |product| %>
<p><%= product[:name] %>, <%= product[:description] %>, <%= product[:price_in_cents] %></p>
<%= link_to image_tag("icon"), "/products/#{product.id}"  %>
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p><%= @product[:name] %>, <%= @product[:description] %>, <%= @product[:price_in_cents] %></p>

<%= link_to "Back to Products", products_url %> | <%= link_to "Edit", edit_product_path(@product) %> | <%= link_to "Delete", @product, :confirm => "Are you sure you want to delete this product?", :method => :delete %>